steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/laravel-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laravel-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'laravel-app', '--image', 'gcr.io/$PROJECT_ID/laravel-app', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/$PROJECT_ID/laravel-app'
